export const countries = [
  { name: "Home", backgroundColor: "#000000", color: "#FFFFFF" },
  { name: "Finland", backgroundColor: "#FFFFFF", color: "#0055A4" },
  { name: "Canada", backgroundColor: "#FF0000", color: "#FFFFFF" },
  { name: "Brazil", backgroundColor: "#009C3B", color: "#FFD700" },
  { name: "Japan", backgroundColor: "#FFFFFF", color: "#BC002D" },
  { name: "Germany", backgroundColor: "#000000", color: "#FFD700" },
  { name: "France", backgroundColor: "#0055A4", color: "#FFFFFF" },
  { name: "Italy", backgroundColor: "#009246", color: "#FFFFFF" },
  { name: "Scotland", backgroundColor: "#00247D", color: "#FFFFFF" },
  { name: "Australia", backgroundColor: "#002868", color: "#FFFFFF" },
  { name: "India", backgroundColor: "#FF9933", color: "#FFFFFF" },
  { name: "China", backgroundColor: "#DE2910", color: "#FFD700" },
  { name: "South Korea", backgroundColor: "#FFFFFF", color: "#003478" },
  { name: "Mexico", backgroundColor: "#006847", color: "#FFFFFF" },
  { name: "Russia", backgroundColor: "#0039A6", color: "#FFFFFF" },
  { name: "Spain", backgroundColor: "#AA151B", color: "#FFD700" },
  { name: "South Africa", backgroundColor: "#007847", color: "#FFFFFF" },
  { name: "Argentina", backgroundColor: "#75AADB", color: "#FFFFFF" },
  { name: "Sweden", backgroundColor: "#006AA7", color: "#FFD700" },
  { name: "Norway", backgroundColor: "#BA0C2F", color: "#FFFFFF" },
  { name: "Egypt", backgroundColor: "#CE1126", color: "#FFD700" },
];
